// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fishjam/media_events/shared.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package fishjam.media_events;

@kotlin.jvm.JvmName("-initializecandidate")
public inline fun candidate(block: fishjam.media_events.CandidateKt.Dsl.() -> kotlin.Unit): fishjam.media_events.Shared.Candidate =
  fishjam.media_events.CandidateKt.Dsl._create(fishjam.media_events.Shared.Candidate.newBuilder()).apply { block() }._build()
/**
 * ```
 * Contains information about an ICE candidate which will be sent to the peer/server
 * ```
 *
 * Protobuf type `fishjam.media_events.Candidate`
 */
public object CandidateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: fishjam.media_events.Shared.Candidate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: fishjam.media_events.Shared.Candidate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): fishjam.media_events.Shared.Candidate = _builder.build()

    /**
     * `string candidate = 1;`
     */
    public var candidate: kotlin.String
      @JvmName("getCandidate")
      get() = _builder.getCandidate()
      @JvmName("setCandidate")
      set(value) {
        _builder.setCandidate(value)
      }
    /**
     * `string candidate = 1;`
     */
    public fun clearCandidate() {
      _builder.clearCandidate()
    }

    /**
     * `int32 sdp_m_line_index = 2;`
     */
    public var sdpMLineIndex: kotlin.Int
      @JvmName("getSdpMLineIndex")
      get() = _builder.getSdpMLineIndex()
      @JvmName("setSdpMLineIndex")
      set(value) {
        _builder.setSdpMLineIndex(value)
      }
    /**
     * `int32 sdp_m_line_index = 2;`
     */
    public fun clearSdpMLineIndex() {
      _builder.clearSdpMLineIndex()
    }

    /**
     * `string sdp_mid = 3;`
     */
    public var sdpMid: kotlin.String
      @JvmName("getSdpMid")
      get() = _builder.getSdpMid()
      @JvmName("setSdpMid")
      set(value) {
        _builder.setSdpMid(value)
      }
    /**
     * `string sdp_mid = 3;`
     */
    public fun clearSdpMid() {
      _builder.clearSdpMid()
    }

    /**
     * `string username_fragment = 4;`
     */
    public var usernameFragment: kotlin.String
      @JvmName("getUsernameFragment")
      get() = _builder.getUsernameFragment()
      @JvmName("setUsernameFragment")
      set(value) {
        _builder.setUsernameFragment(value)
      }
    /**
     * `string username_fragment = 4;`
     */
    public fun clearUsernameFragment() {
      _builder.clearUsernameFragment()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.Shared.Candidate.copy(block: `fishjam.media_events`.CandidateKt.Dsl.() -> kotlin.Unit): fishjam.media_events.Shared.Candidate =
  `fishjam.media_events`.CandidateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

