// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fishjam/media_events/shared.proto
// Protobuf Java Version: 4.26.1

package fishjam.media_events;

public final class Shared {
  private Shared() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Shared.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code fishjam.media_events.Variant}
   */
  public enum Variant
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>VARIANT_UNSPECIFIED = 0;</code>
     */
    VARIANT_UNSPECIFIED(0),
    /**
     * <code>VARIANT_LOW = 1;</code>
     */
    VARIANT_LOW(1),
    /**
     * <code>VARIANT_MEDIUM = 2;</code>
     */
    VARIANT_MEDIUM(2),
    /**
     * <code>VARIANT_HIGH = 3;</code>
     */
    VARIANT_HIGH(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Variant.class.getName());
    }
    /**
     * <code>VARIANT_UNSPECIFIED = 0;</code>
     */
    public static final int VARIANT_UNSPECIFIED_VALUE = 0;
    /**
     * <code>VARIANT_LOW = 1;</code>
     */
    public static final int VARIANT_LOW_VALUE = 1;
    /**
     * <code>VARIANT_MEDIUM = 2;</code>
     */
    public static final int VARIANT_MEDIUM_VALUE = 2;
    /**
     * <code>VARIANT_HIGH = 3;</code>
     */
    public static final int VARIANT_HIGH_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Variant valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Variant forNumber(int value) {
      switch (value) {
        case 0: return VARIANT_UNSPECIFIED;
        case 1: return VARIANT_LOW;
        case 2: return VARIANT_MEDIUM;
        case 3: return VARIANT_HIGH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Variant>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Variant> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Variant>() {
            public Variant findValueByNumber(int number) {
              return Variant.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fishjam.media_events.Shared.getDescriptor().getEnumTypes().get(0);
    }

    private static final Variant[] VALUES = values();

    public static Variant valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Variant(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fishjam.media_events.Variant)
  }

  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fishjam.media_events.Metadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string json = 1;</code>
     * @return The json.
     */
    java.lang.String getJson();
    /**
     * <code>string json = 1;</code>
     * @return The bytes for json.
     */
    com.google.protobuf.ByteString
        getJsonBytes();
  }
  /**
   * Protobuf type {@code fishjam.media_events.Metadata}
   */
  public static final class Metadata extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fishjam.media_events.Metadata)
      MetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Metadata.class.getName());
    }
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Metadata() {
      json_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fishjam.media_events.Shared.internal_static_fishjam_media_events_Metadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fishjam.media_events.Shared.internal_static_fishjam_media_events_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fishjam.media_events.Shared.Metadata.class, fishjam.media_events.Shared.Metadata.Builder.class);
    }

    public static final int JSON_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object json_ = "";
    /**
     * <code>string json = 1;</code>
     * @return The json.
     */
    @java.lang.Override
    public java.lang.String getJson() {
      java.lang.Object ref = json_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        json_ = s;
        return s;
      }
    }
    /**
     * <code>string json = 1;</code>
     * @return The bytes for json.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJsonBytes() {
      java.lang.Object ref = json_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        json_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(json_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, json_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(json_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, json_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fishjam.media_events.Shared.Metadata)) {
        return super.equals(obj);
      }
      fishjam.media_events.Shared.Metadata other = (fishjam.media_events.Shared.Metadata) obj;

      if (!getJson()
          .equals(other.getJson())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSON_FIELD_NUMBER;
      hash = (53 * hash) + getJson().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fishjam.media_events.Shared.Metadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fishjam.media_events.Shared.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fishjam.media_events.Shared.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fishjam.media_events.Shared.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fishjam.media_events.Shared.Metadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fishjam.media_events.Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fishjam.media_events.Metadata)
        fishjam.media_events.Shared.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_Metadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fishjam.media_events.Shared.Metadata.class, fishjam.media_events.Shared.Metadata.Builder.class);
      }

      // Construct using fishjam.media_events.Shared.Metadata.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        json_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_Metadata_descriptor;
      }

      @java.lang.Override
      public fishjam.media_events.Shared.Metadata getDefaultInstanceForType() {
        return fishjam.media_events.Shared.Metadata.getDefaultInstance();
      }

      @java.lang.Override
      public fishjam.media_events.Shared.Metadata build() {
        fishjam.media_events.Shared.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fishjam.media_events.Shared.Metadata buildPartial() {
        fishjam.media_events.Shared.Metadata result = new fishjam.media_events.Shared.Metadata(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(fishjam.media_events.Shared.Metadata result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.json_ = json_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fishjam.media_events.Shared.Metadata) {
          return mergeFrom((fishjam.media_events.Shared.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fishjam.media_events.Shared.Metadata other) {
        if (other == fishjam.media_events.Shared.Metadata.getDefaultInstance()) return this;
        if (!other.getJson().isEmpty()) {
          json_ = other.json_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                json_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object json_ = "";
      /**
       * <code>string json = 1;</code>
       * @return The json.
       */
      public java.lang.String getJson() {
        java.lang.Object ref = json_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          json_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string json = 1;</code>
       * @return The bytes for json.
       */
      public com.google.protobuf.ByteString
          getJsonBytes() {
        java.lang.Object ref = json_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          json_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string json = 1;</code>
       * @param value The json to set.
       * @return This builder for chaining.
       */
      public Builder setJson(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        json_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string json = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJson() {
        json_ = getDefaultInstance().getJson();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string json = 1;</code>
       * @param value The bytes for json to set.
       * @return This builder for chaining.
       */
      public Builder setJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        json_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fishjam.media_events.Metadata)
    }

    // @@protoc_insertion_point(class_scope:fishjam.media_events.Metadata)
    private static final fishjam.media_events.Shared.Metadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fishjam.media_events.Shared.Metadata();
    }

    public static fishjam.media_events.Shared.Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Metadata>
        PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
      @java.lang.Override
      public Metadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Metadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fishjam.media_events.Shared.Metadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MidToTrackIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fishjam.media_events.MidToTrackId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mid = 1;</code>
     * @return The mid.
     */
    java.lang.String getMid();
    /**
     * <code>string mid = 1;</code>
     * @return The bytes for mid.
     */
    com.google.protobuf.ByteString
        getMidBytes();

    /**
     * <code>string track_id = 2;</code>
     * @return The trackId.
     */
    java.lang.String getTrackId();
    /**
     * <code>string track_id = 2;</code>
     * @return The bytes for trackId.
     */
    com.google.protobuf.ByteString
        getTrackIdBytes();
  }
  /**
   * Protobuf type {@code fishjam.media_events.MidToTrackId}
   */
  public static final class MidToTrackId extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fishjam.media_events.MidToTrackId)
      MidToTrackIdOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        MidToTrackId.class.getName());
    }
    // Use MidToTrackId.newBuilder() to construct.
    private MidToTrackId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MidToTrackId() {
      mid_ = "";
      trackId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fishjam.media_events.Shared.internal_static_fishjam_media_events_MidToTrackId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fishjam.media_events.Shared.internal_static_fishjam_media_events_MidToTrackId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fishjam.media_events.Shared.MidToTrackId.class, fishjam.media_events.Shared.MidToTrackId.Builder.class);
    }

    public static final int MID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mid_ = "";
    /**
     * <code>string mid = 1;</code>
     * @return The mid.
     */
    @java.lang.Override
    public java.lang.String getMid() {
      java.lang.Object ref = mid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mid_ = s;
        return s;
      }
    }
    /**
     * <code>string mid = 1;</code>
     * @return The bytes for mid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMidBytes() {
      java.lang.Object ref = mid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACK_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object trackId_ = "";
    /**
     * <code>string track_id = 2;</code>
     * @return The trackId.
     */
    @java.lang.Override
    public java.lang.String getTrackId() {
      java.lang.Object ref = trackId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        trackId_ = s;
        return s;
      }
    }
    /**
     * <code>string track_id = 2;</code>
     * @return The bytes for trackId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrackIdBytes() {
      java.lang.Object ref = trackId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trackId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, mid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trackId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, trackId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, mid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trackId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, trackId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fishjam.media_events.Shared.MidToTrackId)) {
        return super.equals(obj);
      }
      fishjam.media_events.Shared.MidToTrackId other = (fishjam.media_events.Shared.MidToTrackId) obj;

      if (!getMid()
          .equals(other.getMid())) return false;
      if (!getTrackId()
          .equals(other.getTrackId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MID_FIELD_NUMBER;
      hash = (53 * hash) + getMid().hashCode();
      hash = (37 * hash) + TRACK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTrackId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fishjam.media_events.Shared.MidToTrackId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fishjam.media_events.Shared.MidToTrackId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fishjam.media_events.Shared.MidToTrackId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fishjam.media_events.Shared.MidToTrackId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fishjam.media_events.Shared.MidToTrackId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fishjam.media_events.MidToTrackId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fishjam.media_events.MidToTrackId)
        fishjam.media_events.Shared.MidToTrackIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_MidToTrackId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_MidToTrackId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fishjam.media_events.Shared.MidToTrackId.class, fishjam.media_events.Shared.MidToTrackId.Builder.class);
      }

      // Construct using fishjam.media_events.Shared.MidToTrackId.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mid_ = "";
        trackId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_MidToTrackId_descriptor;
      }

      @java.lang.Override
      public fishjam.media_events.Shared.MidToTrackId getDefaultInstanceForType() {
        return fishjam.media_events.Shared.MidToTrackId.getDefaultInstance();
      }

      @java.lang.Override
      public fishjam.media_events.Shared.MidToTrackId build() {
        fishjam.media_events.Shared.MidToTrackId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fishjam.media_events.Shared.MidToTrackId buildPartial() {
        fishjam.media_events.Shared.MidToTrackId result = new fishjam.media_events.Shared.MidToTrackId(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(fishjam.media_events.Shared.MidToTrackId result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mid_ = mid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.trackId_ = trackId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fishjam.media_events.Shared.MidToTrackId) {
          return mergeFrom((fishjam.media_events.Shared.MidToTrackId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fishjam.media_events.Shared.MidToTrackId other) {
        if (other == fishjam.media_events.Shared.MidToTrackId.getDefaultInstance()) return this;
        if (!other.getMid().isEmpty()) {
          mid_ = other.mid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTrackId().isEmpty()) {
          trackId_ = other.trackId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                mid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                trackId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object mid_ = "";
      /**
       * <code>string mid = 1;</code>
       * @return The mid.
       */
      public java.lang.String getMid() {
        java.lang.Object ref = mid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mid = 1;</code>
       * @return The bytes for mid.
       */
      public com.google.protobuf.ByteString
          getMidBytes() {
        java.lang.Object ref = mid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mid = 1;</code>
       * @param value The mid to set.
       * @return This builder for chaining.
       */
      public Builder setMid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string mid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMid() {
        mid_ = getDefaultInstance().getMid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string mid = 1;</code>
       * @param value The bytes for mid to set.
       * @return This builder for chaining.
       */
      public Builder setMidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object trackId_ = "";
      /**
       * <code>string track_id = 2;</code>
       * @return The trackId.
       */
      public java.lang.String getTrackId() {
        java.lang.Object ref = trackId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          trackId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string track_id = 2;</code>
       * @return The bytes for trackId.
       */
      public com.google.protobuf.ByteString
          getTrackIdBytes() {
        java.lang.Object ref = trackId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trackId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string track_id = 2;</code>
       * @param value The trackId to set.
       * @return This builder for chaining.
       */
      public Builder setTrackId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        trackId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string track_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrackId() {
        trackId_ = getDefaultInstance().getTrackId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string track_id = 2;</code>
       * @param value The bytes for trackId to set.
       * @return This builder for chaining.
       */
      public Builder setTrackIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        trackId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fishjam.media_events.MidToTrackId)
    }

    // @@protoc_insertion_point(class_scope:fishjam.media_events.MidToTrackId)
    private static final fishjam.media_events.Shared.MidToTrackId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fishjam.media_events.Shared.MidToTrackId();
    }

    public static fishjam.media_events.Shared.MidToTrackId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MidToTrackId>
        PARSER = new com.google.protobuf.AbstractParser<MidToTrackId>() {
      @java.lang.Override
      public MidToTrackId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MidToTrackId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MidToTrackId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fishjam.media_events.Shared.MidToTrackId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CandidateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fishjam.media_events.Candidate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string candidate = 1;</code>
     * @return The candidate.
     */
    java.lang.String getCandidate();
    /**
     * <code>string candidate = 1;</code>
     * @return The bytes for candidate.
     */
    com.google.protobuf.ByteString
        getCandidateBytes();

    /**
     * <code>int32 sdp_m_line_index = 2;</code>
     * @return The sdpMLineIndex.
     */
    int getSdpMLineIndex();

    /**
     * <code>string sdp_mid = 3;</code>
     * @return The sdpMid.
     */
    java.lang.String getSdpMid();
    /**
     * <code>string sdp_mid = 3;</code>
     * @return The bytes for sdpMid.
     */
    com.google.protobuf.ByteString
        getSdpMidBytes();

    /**
     * <code>string username_fragment = 4;</code>
     * @return The usernameFragment.
     */
    java.lang.String getUsernameFragment();
    /**
     * <code>string username_fragment = 4;</code>
     * @return The bytes for usernameFragment.
     */
    com.google.protobuf.ByteString
        getUsernameFragmentBytes();
  }
  /**
   * <pre>
   * Contains information about an ICE candidate which will be sent to the peer/server
   * </pre>
   *
   * Protobuf type {@code fishjam.media_events.Candidate}
   */
  public static final class Candidate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fishjam.media_events.Candidate)
      CandidateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Candidate.class.getName());
    }
    // Use Candidate.newBuilder() to construct.
    private Candidate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Candidate() {
      candidate_ = "";
      sdpMid_ = "";
      usernameFragment_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fishjam.media_events.Shared.internal_static_fishjam_media_events_Candidate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fishjam.media_events.Shared.internal_static_fishjam_media_events_Candidate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fishjam.media_events.Shared.Candidate.class, fishjam.media_events.Shared.Candidate.Builder.class);
    }

    public static final int CANDIDATE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object candidate_ = "";
    /**
     * <code>string candidate = 1;</code>
     * @return The candidate.
     */
    @java.lang.Override
    public java.lang.String getCandidate() {
      java.lang.Object ref = candidate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidate_ = s;
        return s;
      }
    }
    /**
     * <code>string candidate = 1;</code>
     * @return The bytes for candidate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCandidateBytes() {
      java.lang.Object ref = candidate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDP_M_LINE_INDEX_FIELD_NUMBER = 2;
    private int sdpMLineIndex_ = 0;
    /**
     * <code>int32 sdp_m_line_index = 2;</code>
     * @return The sdpMLineIndex.
     */
    @java.lang.Override
    public int getSdpMLineIndex() {
      return sdpMLineIndex_;
    }

    public static final int SDP_MID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sdpMid_ = "";
    /**
     * <code>string sdp_mid = 3;</code>
     * @return The sdpMid.
     */
    @java.lang.Override
    public java.lang.String getSdpMid() {
      java.lang.Object ref = sdpMid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdpMid_ = s;
        return s;
      }
    }
    /**
     * <code>string sdp_mid = 3;</code>
     * @return The bytes for sdpMid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSdpMidBytes() {
      java.lang.Object ref = sdpMid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdpMid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FRAGMENT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object usernameFragment_ = "";
    /**
     * <code>string username_fragment = 4;</code>
     * @return The usernameFragment.
     */
    @java.lang.Override
    public java.lang.String getUsernameFragment() {
      java.lang.Object ref = usernameFragment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usernameFragment_ = s;
        return s;
      }
    }
    /**
     * <code>string username_fragment = 4;</code>
     * @return The bytes for usernameFragment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameFragmentBytes() {
      java.lang.Object ref = usernameFragment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usernameFragment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(candidate_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, candidate_);
      }
      if (sdpMLineIndex_ != 0) {
        output.writeInt32(2, sdpMLineIndex_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sdpMid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, sdpMid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(usernameFragment_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, usernameFragment_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(candidate_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, candidate_);
      }
      if (sdpMLineIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sdpMLineIndex_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sdpMid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, sdpMid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(usernameFragment_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, usernameFragment_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fishjam.media_events.Shared.Candidate)) {
        return super.equals(obj);
      }
      fishjam.media_events.Shared.Candidate other = (fishjam.media_events.Shared.Candidate) obj;

      if (!getCandidate()
          .equals(other.getCandidate())) return false;
      if (getSdpMLineIndex()
          != other.getSdpMLineIndex()) return false;
      if (!getSdpMid()
          .equals(other.getSdpMid())) return false;
      if (!getUsernameFragment()
          .equals(other.getUsernameFragment())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CANDIDATE_FIELD_NUMBER;
      hash = (53 * hash) + getCandidate().hashCode();
      hash = (37 * hash) + SDP_M_LINE_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getSdpMLineIndex();
      hash = (37 * hash) + SDP_MID_FIELD_NUMBER;
      hash = (53 * hash) + getSdpMid().hashCode();
      hash = (37 * hash) + USERNAME_FRAGMENT_FIELD_NUMBER;
      hash = (53 * hash) + getUsernameFragment().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fishjam.media_events.Shared.Candidate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fishjam.media_events.Shared.Candidate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fishjam.media_events.Shared.Candidate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fishjam.media_events.Shared.Candidate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fishjam.media_events.Shared.Candidate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Contains information about an ICE candidate which will be sent to the peer/server
     * </pre>
     *
     * Protobuf type {@code fishjam.media_events.Candidate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fishjam.media_events.Candidate)
        fishjam.media_events.Shared.CandidateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_Candidate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_Candidate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fishjam.media_events.Shared.Candidate.class, fishjam.media_events.Shared.Candidate.Builder.class);
      }

      // Construct using fishjam.media_events.Shared.Candidate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        candidate_ = "";
        sdpMLineIndex_ = 0;
        sdpMid_ = "";
        usernameFragment_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fishjam.media_events.Shared.internal_static_fishjam_media_events_Candidate_descriptor;
      }

      @java.lang.Override
      public fishjam.media_events.Shared.Candidate getDefaultInstanceForType() {
        return fishjam.media_events.Shared.Candidate.getDefaultInstance();
      }

      @java.lang.Override
      public fishjam.media_events.Shared.Candidate build() {
        fishjam.media_events.Shared.Candidate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fishjam.media_events.Shared.Candidate buildPartial() {
        fishjam.media_events.Shared.Candidate result = new fishjam.media_events.Shared.Candidate(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(fishjam.media_events.Shared.Candidate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.candidate_ = candidate_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sdpMLineIndex_ = sdpMLineIndex_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sdpMid_ = sdpMid_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.usernameFragment_ = usernameFragment_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fishjam.media_events.Shared.Candidate) {
          return mergeFrom((fishjam.media_events.Shared.Candidate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fishjam.media_events.Shared.Candidate other) {
        if (other == fishjam.media_events.Shared.Candidate.getDefaultInstance()) return this;
        if (!other.getCandidate().isEmpty()) {
          candidate_ = other.candidate_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getSdpMLineIndex() != 0) {
          setSdpMLineIndex(other.getSdpMLineIndex());
        }
        if (!other.getSdpMid().isEmpty()) {
          sdpMid_ = other.sdpMid_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getUsernameFragment().isEmpty()) {
          usernameFragment_ = other.usernameFragment_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                candidate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                sdpMLineIndex_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                sdpMid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                usernameFragment_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object candidate_ = "";
      /**
       * <code>string candidate = 1;</code>
       * @return The candidate.
       */
      public java.lang.String getCandidate() {
        java.lang.Object ref = candidate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          candidate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string candidate = 1;</code>
       * @return The bytes for candidate.
       */
      public com.google.protobuf.ByteString
          getCandidateBytes() {
        java.lang.Object ref = candidate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          candidate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string candidate = 1;</code>
       * @param value The candidate to set.
       * @return This builder for chaining.
       */
      public Builder setCandidate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        candidate_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string candidate = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCandidate() {
        candidate_ = getDefaultInstance().getCandidate();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string candidate = 1;</code>
       * @param value The bytes for candidate to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        candidate_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int sdpMLineIndex_ ;
      /**
       * <code>int32 sdp_m_line_index = 2;</code>
       * @return The sdpMLineIndex.
       */
      @java.lang.Override
      public int getSdpMLineIndex() {
        return sdpMLineIndex_;
      }
      /**
       * <code>int32 sdp_m_line_index = 2;</code>
       * @param value The sdpMLineIndex to set.
       * @return This builder for chaining.
       */
      public Builder setSdpMLineIndex(int value) {

        sdpMLineIndex_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sdp_m_line_index = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSdpMLineIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sdpMLineIndex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sdpMid_ = "";
      /**
       * <code>string sdp_mid = 3;</code>
       * @return The sdpMid.
       */
      public java.lang.String getSdpMid() {
        java.lang.Object ref = sdpMid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sdpMid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sdp_mid = 3;</code>
       * @return The bytes for sdpMid.
       */
      public com.google.protobuf.ByteString
          getSdpMidBytes() {
        java.lang.Object ref = sdpMid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdpMid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sdp_mid = 3;</code>
       * @param value The sdpMid to set.
       * @return This builder for chaining.
       */
      public Builder setSdpMid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sdpMid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string sdp_mid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSdpMid() {
        sdpMid_ = getDefaultInstance().getSdpMid();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string sdp_mid = 3;</code>
       * @param value The bytes for sdpMid to set.
       * @return This builder for chaining.
       */
      public Builder setSdpMidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sdpMid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object usernameFragment_ = "";
      /**
       * <code>string username_fragment = 4;</code>
       * @return The usernameFragment.
       */
      public java.lang.String getUsernameFragment() {
        java.lang.Object ref = usernameFragment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          usernameFragment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username_fragment = 4;</code>
       * @return The bytes for usernameFragment.
       */
      public com.google.protobuf.ByteString
          getUsernameFragmentBytes() {
        java.lang.Object ref = usernameFragment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usernameFragment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username_fragment = 4;</code>
       * @param value The usernameFragment to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameFragment(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        usernameFragment_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string username_fragment = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsernameFragment() {
        usernameFragment_ = getDefaultInstance().getUsernameFragment();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string username_fragment = 4;</code>
       * @param value The bytes for usernameFragment to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameFragmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        usernameFragment_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fishjam.media_events.Candidate)
    }

    // @@protoc_insertion_point(class_scope:fishjam.media_events.Candidate)
    private static final fishjam.media_events.Shared.Candidate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fishjam.media_events.Shared.Candidate();
    }

    public static fishjam.media_events.Shared.Candidate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Candidate>
        PARSER = new com.google.protobuf.AbstractParser<Candidate>() {
      @java.lang.Override
      public Candidate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Candidate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Candidate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fishjam.media_events.Shared.Candidate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fishjam_media_events_Metadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fishjam_media_events_Metadata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fishjam_media_events_MidToTrackId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fishjam_media_events_MidToTrackId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fishjam_media_events_Candidate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fishjam_media_events_Candidate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!fishjam/media_events/shared.proto\022\024fis" +
      "hjam.media_events\"\030\n\010Metadata\022\014\n\004json\030\001 " +
      "\001(\t\"-\n\014MidToTrackId\022\013\n\003mid\030\001 \001(\t\022\020\n\010trac" +
      "k_id\030\002 \001(\t\"d\n\tCandidate\022\021\n\tcandidate\030\001 \001" +
      "(\t\022\030\n\020sdp_m_line_index\030\002 \001(\005\022\017\n\007sdp_mid\030" +
      "\003 \001(\t\022\031\n\021username_fragment\030\004 \001(\t*Y\n\007Vari" +
      "ant\022\027\n\023VARIANT_UNSPECIFIED\020\000\022\017\n\013VARIANT_" +
      "LOW\020\001\022\022\n\016VARIANT_MEDIUM\020\002\022\020\n\014VARIANT_HIG" +
      "H\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fishjam_media_events_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fishjam_media_events_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fishjam_media_events_Metadata_descriptor,
        new java.lang.String[] { "Json", });
    internal_static_fishjam_media_events_MidToTrackId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fishjam_media_events_MidToTrackId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fishjam_media_events_MidToTrackId_descriptor,
        new java.lang.String[] { "Mid", "TrackId", });
    internal_static_fishjam_media_events_Candidate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fishjam_media_events_Candidate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fishjam_media_events_Candidate_descriptor,
        new java.lang.String[] { "Candidate", "SdpMLineIndex", "SdpMid", "UsernameFragment", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
