// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fishjam/media_events/shared.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package fishjam.media_events;

