internal protocol RTCEngineListener: AnyObject {
    func onSendMediaEvent(event: Fishjam_MediaEvents_Peer_MediaEvent.OneOf_Content)
    func onConnected(endpointId: String, endpoints: [Fishjam_MediaEvents_Server_MediaEvent.Endpoint])
    func onEndpointAdded(endpointId: String, metadata: Metadata?)
    func onEndpointRemoved(endpointId: String)
    func onEndpointUpdated(endpointId: String, metadata: Metadata?)
    func onOfferData(tracksTypes: Fishjam_MediaEvents_Server_MediaEvent.OfferData.TrackTypes)
    func onSdpAnswer(sdpAnswer: String, midToTrackId: [Fishjam_MediaEvents_MidToTrackId])
    func onRemoteCandidate(candidate: String, sdpMLineIndex: Int32, sdpMid: String?)
    func onTracksAdded(endpointId: String, tracks: [Fishjam_MediaEvents_Server_MediaEvent.Track])
    func onTracksRemoved(endpointId: String, trackIds: [String])
    func onTrackUpdated(endpointId: String, trackId: String, metadata: Metadata)
    func onTrackEncodingChanged(endpointId: String, trackId: String, encoding: String, encodingReason: String)
    func onVadNotification(trackId: String, status: Fishjam_MediaEvents_Server_MediaEvent.VadNotification.Status)
    func onBandwidthEstimation(estimation: Int)
}
