name: "Publish React Native Client"
description: "Publishes the React Native client package to NPM"
inputs:
  npm-token:
    description: "NPM token for publishing"
    required: true

runs:
  using: "composite"
  steps:
    - run: corepack enable
      shell: bash
    - run: yarn
      shell: bash
    - run: yarn prepare
      shell: bash
    - name: Publish to NPM
      run: yarn npm publish --access public
      working-directory: packages/react-native-client
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      shell: bash
