// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fishjam/media_events/peer/peer.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package fishjam.media_events.peer;

@kotlin.jvm.JvmName("-initializemediaEvent")
public inline fun mediaEvent(block: fishjam.media_events.peer.MediaEventKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent =
  fishjam.media_events.peer.MediaEventKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.newBuilder()).apply { block() }._build()
/**
 * ```
 * Defines any type of message sent from Peer to Membrane RTC Engine
 * ```
 *
 * Protobuf type `fishjam.media_events.peer.MediaEvent`
 */
public object MediaEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: fishjam.media_events.peer.Peer.MediaEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent = _builder.build()

    /**
     * `.fishjam.media_events.peer.MediaEvent.Connect connect = 1;`
     */
    public var connect: fishjam.media_events.peer.Peer.MediaEvent.Connect
      @JvmName("getConnect")
      get() = _builder.getConnect()
      @JvmName("setConnect")
      set(value) {
        _builder.setConnect(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.Connect connect = 1;`
     */
    public fun clearConnect() {
      _builder.clearConnect()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.Connect connect = 1;`
     * @return Whether the connect field is set.
     */
    public fun hasConnect(): kotlin.Boolean {
      return _builder.hasConnect()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.Disconnect disconnect = 2;`
     */
    public var disconnect: fishjam.media_events.peer.Peer.MediaEvent.Disconnect
      @JvmName("getDisconnect")
      get() = _builder.getDisconnect()
      @JvmName("setDisconnect")
      set(value) {
        _builder.setDisconnect(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.Disconnect disconnect = 2;`
     */
    public fun clearDisconnect() {
      _builder.clearDisconnect()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.Disconnect disconnect = 2;`
     * @return Whether the disconnect field is set.
     */
    public fun hasDisconnect(): kotlin.Boolean {
      return _builder.hasDisconnect()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.UpdateEndpointMetadata update_endpoint_metadata = 3;`
     */
    public var updateEndpointMetadata: fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata
      @JvmName("getUpdateEndpointMetadata")
      get() = _builder.getUpdateEndpointMetadata()
      @JvmName("setUpdateEndpointMetadata")
      set(value) {
        _builder.setUpdateEndpointMetadata(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.UpdateEndpointMetadata update_endpoint_metadata = 3;`
     */
    public fun clearUpdateEndpointMetadata() {
      _builder.clearUpdateEndpointMetadata()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.UpdateEndpointMetadata update_endpoint_metadata = 3;`
     * @return Whether the updateEndpointMetadata field is set.
     */
    public fun hasUpdateEndpointMetadata(): kotlin.Boolean {
      return _builder.hasUpdateEndpointMetadata()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.UpdateTrackMetadata update_track_metadata = 4;`
     */
    public var updateTrackMetadata: fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata
      @JvmName("getUpdateTrackMetadata")
      get() = _builder.getUpdateTrackMetadata()
      @JvmName("setUpdateTrackMetadata")
      set(value) {
        _builder.setUpdateTrackMetadata(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.UpdateTrackMetadata update_track_metadata = 4;`
     */
    public fun clearUpdateTrackMetadata() {
      _builder.clearUpdateTrackMetadata()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.UpdateTrackMetadata update_track_metadata = 4;`
     * @return Whether the updateTrackMetadata field is set.
     */
    public fun hasUpdateTrackMetadata(): kotlin.Boolean {
      return _builder.hasUpdateTrackMetadata()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.RenegotiateTracks renegotiate_tracks = 5;`
     */
    public var renegotiateTracks: fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks
      @JvmName("getRenegotiateTracks")
      get() = _builder.getRenegotiateTracks()
      @JvmName("setRenegotiateTracks")
      set(value) {
        _builder.setRenegotiateTracks(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.RenegotiateTracks renegotiate_tracks = 5;`
     */
    public fun clearRenegotiateTracks() {
      _builder.clearRenegotiateTracks()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.RenegotiateTracks renegotiate_tracks = 5;`
     * @return Whether the renegotiateTracks field is set.
     */
    public fun hasRenegotiateTracks(): kotlin.Boolean {
      return _builder.hasRenegotiateTracks()
    }

    /**
     * `.fishjam.media_events.Candidate candidate = 6;`
     */
    public var candidate: fishjam.media_events.Shared.Candidate
      @JvmName("getCandidate")
      get() = _builder.getCandidate()
      @JvmName("setCandidate")
      set(value) {
        _builder.setCandidate(value)
      }
    /**
     * `.fishjam.media_events.Candidate candidate = 6;`
     */
    public fun clearCandidate() {
      _builder.clearCandidate()
    }
    /**
     * `.fishjam.media_events.Candidate candidate = 6;`
     * @return Whether the candidate field is set.
     */
    public fun hasCandidate(): kotlin.Boolean {
      return _builder.hasCandidate()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.SdpOffer sdp_offer = 7;`
     */
    public var sdpOffer: fishjam.media_events.peer.Peer.MediaEvent.SdpOffer
      @JvmName("getSdpOffer")
      get() = _builder.getSdpOffer()
      @JvmName("setSdpOffer")
      set(value) {
        _builder.setSdpOffer(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.SdpOffer sdp_offer = 7;`
     */
    public fun clearSdpOffer() {
      _builder.clearSdpOffer()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.SdpOffer sdp_offer = 7;`
     * @return Whether the sdpOffer field is set.
     */
    public fun hasSdpOffer(): kotlin.Boolean {
      return _builder.hasSdpOffer()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.TrackBitrates track_bitrates = 8;`
     */
    public var trackBitrates: fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates
      @JvmName("getTrackBitrates")
      get() = _builder.getTrackBitrates()
      @JvmName("setTrackBitrates")
      set(value) {
        _builder.setTrackBitrates(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.TrackBitrates track_bitrates = 8;`
     */
    public fun clearTrackBitrates() {
      _builder.clearTrackBitrates()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.TrackBitrates track_bitrates = 8;`
     * @return Whether the trackBitrates field is set.
     */
    public fun hasTrackBitrates(): kotlin.Boolean {
      return _builder.hasTrackBitrates()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.EnableTrackVariant enable_track_variant = 9;`
     */
    public var enableTrackVariant: fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant
      @JvmName("getEnableTrackVariant")
      get() = _builder.getEnableTrackVariant()
      @JvmName("setEnableTrackVariant")
      set(value) {
        _builder.setEnableTrackVariant(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.EnableTrackVariant enable_track_variant = 9;`
     */
    public fun clearEnableTrackVariant() {
      _builder.clearEnableTrackVariant()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.EnableTrackVariant enable_track_variant = 9;`
     * @return Whether the enableTrackVariant field is set.
     */
    public fun hasEnableTrackVariant(): kotlin.Boolean {
      return _builder.hasEnableTrackVariant()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.DisableTrackVariant disable_track_variant = 10;`
     */
    public var disableTrackVariant: fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant
      @JvmName("getDisableTrackVariant")
      get() = _builder.getDisableTrackVariant()
      @JvmName("setDisableTrackVariant")
      set(value) {
        _builder.setDisableTrackVariant(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.DisableTrackVariant disable_track_variant = 10;`
     */
    public fun clearDisableTrackVariant() {
      _builder.clearDisableTrackVariant()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.DisableTrackVariant disable_track_variant = 10;`
     * @return Whether the disableTrackVariant field is set.
     */
    public fun hasDisableTrackVariant(): kotlin.Boolean {
      return _builder.hasDisableTrackVariant()
    }

    /**
     * `.fishjam.media_events.peer.MediaEvent.SetTargetTrackVariant set_target_track_variant = 11;`
     */
    public var setTargetTrackVariant: fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant
      @JvmName("getSetTargetTrackVariant")
      get() = _builder.getSetTargetTrackVariant()
      @JvmName("setSetTargetTrackVariant")
      set(value) {
        _builder.setSetTargetTrackVariant(value)
      }
    /**
     * `.fishjam.media_events.peer.MediaEvent.SetTargetTrackVariant set_target_track_variant = 11;`
     */
    public fun clearSetTargetTrackVariant() {
      _builder.clearSetTargetTrackVariant()
    }
    /**
     * `.fishjam.media_events.peer.MediaEvent.SetTargetTrackVariant set_target_track_variant = 11;`
     * @return Whether the setTargetTrackVariant field is set.
     */
    public fun hasSetTargetTrackVariant(): kotlin.Boolean {
      return _builder.hasSetTargetTrackVariant()
    }
    public val contentCase: fishjam.media_events.peer.Peer.MediaEvent.ContentCase
      @JvmName("getContentCase")
      get() = _builder.getContentCase()

    public fun clearContent() {
      _builder.clearContent()
    }
  }
  @kotlin.jvm.JvmName("-initializevariantBitrate")
  public inline fun variantBitrate(block: fishjam.media_events.peer.MediaEventKt.VariantBitrateKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate =
    fishjam.media_events.peer.MediaEventKt.VariantBitrateKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `fishjam.media_events.peer.MediaEvent.VariantBitrate`
   */
  public object VariantBitrateKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate = _builder.build()

      /**
       * `.fishjam.media_events.Variant variant = 1;`
       */
      public var variant: fishjam.media_events.Shared.Variant
        @JvmName("getVariant")
        get() = _builder.getVariant()
        @JvmName("setVariant")
        set(value) {
          _builder.setVariant(value)
        }
      public var variantValue: kotlin.Int
        @JvmName("getVariantValue")
        get() = _builder.getVariantValue()
        @JvmName("setVariantValue")
        set(value) {
          _builder.setVariantValue(value)
        }
      /**
       * `.fishjam.media_events.Variant variant = 1;`
       */
      public fun clearVariant() {
        _builder.clearVariant()
      }

      /**
       * `int32 bitrate = 2;`
       */
      public var bitrate: kotlin.Int
        @JvmName("getBitrate")
        get() = _builder.getBitrate()
        @JvmName("setBitrate")
        set(value) {
          _builder.setBitrate(value)
        }
      /**
       * `int32 bitrate = 2;`
       */
      public fun clearBitrate() {
        _builder.clearBitrate()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeconnect")
  public inline fun connect(block: fishjam.media_events.peer.MediaEventKt.ConnectKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.Connect =
    fishjam.media_events.peer.MediaEventKt.ConnectKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.Connect.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent when a peer wants to join WebRTC Endpoint.
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.Connect`
   */
  public object ConnectKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.Connect.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.Connect.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.Connect = _builder.build()

      /**
       * `string metadata_json = 1;`
       */
      public var metadataJson: kotlin.String
        @JvmName("getMetadataJson")
        get() = _builder.getMetadataJson()
        @JvmName("setMetadataJson")
        set(value) {
          _builder.setMetadataJson(value)
        }
      /**
       * `string metadata_json = 1;`
       */
      public fun clearMetadataJson() {
        _builder.clearMetadataJson()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializedisconnect")
  public inline fun disconnect(block: fishjam.media_events.peer.MediaEventKt.DisconnectKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.Disconnect =
    fishjam.media_events.peer.MediaEventKt.DisconnectKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.Disconnect.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent when a peer disconnects from WebRTC Endpoint.
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.Disconnect`
   */
  public object DisconnectKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.Disconnect.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.Disconnect.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.Disconnect = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializeupdateEndpointMetadata")
  public inline fun updateEndpointMetadata(block: fishjam.media_events.peer.MediaEventKt.UpdateEndpointMetadataKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata =
    fishjam.media_events.peer.MediaEventKt.UpdateEndpointMetadataKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent when a peer wants to update its metadata
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.UpdateEndpointMetadata`
   */
  public object UpdateEndpointMetadataKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata = _builder.build()

      /**
       * `string metadata_json = 1;`
       */
      public var metadataJson: kotlin.String
        @JvmName("getMetadataJson")
        get() = _builder.getMetadataJson()
        @JvmName("setMetadataJson")
        set(value) {
          _builder.setMetadataJson(value)
        }
      /**
       * `string metadata_json = 1;`
       */
      public fun clearMetadataJson() {
        _builder.clearMetadataJson()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeupdateTrackMetadata")
  public inline fun updateTrackMetadata(block: fishjam.media_events.peer.MediaEventKt.UpdateTrackMetadataKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata =
    fishjam.media_events.peer.MediaEventKt.UpdateTrackMetadataKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent when a peer wants to update its track's metadata
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.UpdateTrackMetadata`
   */
  public object UpdateTrackMetadataKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata = _builder.build()

      /**
       * `string track_id = 1;`
       */
      public var trackId: kotlin.String
        @JvmName("getTrackId")
        get() = _builder.getTrackId()
        @JvmName("setTrackId")
        set(value) {
          _builder.setTrackId(value)
        }
      /**
       * `string track_id = 1;`
       */
      public fun clearTrackId() {
        _builder.clearTrackId()
      }

      /**
       * `string metadata_json = 2;`
       */
      public var metadataJson: kotlin.String
        @JvmName("getMetadataJson")
        get() = _builder.getMetadataJson()
        @JvmName("setMetadataJson")
        set(value) {
          _builder.setMetadataJson(value)
        }
      /**
       * `string metadata_json = 2;`
       */
      public fun clearMetadataJson() {
        _builder.clearMetadataJson()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializerenegotiateTracks")
  public inline fun renegotiateTracks(block: fishjam.media_events.peer.MediaEventKt.RenegotiateTracksKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks =
    fishjam.media_events.peer.MediaEventKt.RenegotiateTracksKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent when peer wants to renegatiate connection due to adding a track or removing a track
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.RenegotiateTracks`
   */
  public object RenegotiateTracksKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializesdpOffer")
  public inline fun sdpOffer(block: fishjam.media_events.peer.MediaEventKt.SdpOfferKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.SdpOffer =
    fishjam.media_events.peer.MediaEventKt.SdpOfferKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.SdpOffer.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent as a response to `offerData` media event during renegotiation
   * Maps contain only information about current peer's `sendonly` tracks.
   * The "mid" is an identifier used to associate an RTP packet with an MLine from the SDP offer/answer.
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.SdpOffer`
   */
  public object SdpOfferKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.SdpOffer.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.SdpOffer.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.SdpOffer = _builder.build()

      /**
       * ```
       * The value of the `sessionDescription.sdp`
       * ```
       *
       * `string sdp = 1;`
       */
      public var sdp: kotlin.String
        @JvmName("getSdp")
        get() = _builder.getSdp()
        @JvmName("setSdp")
        set(value) {
          _builder.setSdp(value)
        }
      /**
       * ```
       * The value of the `sessionDescription.sdp`
       * ```
       *
       * `string sdp = 1;`
       */
      public fun clearSdp() {
        _builder.clearSdp()
      }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class TrackIdToMetadataJsonProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `map<string, string> track_id_to_metadata_json = 2;`
       */
       public val trackIdToMetadataJson: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TrackIdToMetadataJsonProxy>
        @kotlin.jvm.JvmSynthetic
        @JvmName("getTrackIdToMetadataJsonMap")
        get() = com.google.protobuf.kotlin.DslMap(
          _builder.getTrackIdToMetadataJsonMap()
        )
      /**
       * `map<string, string> track_id_to_metadata_json = 2;`
       */
      @JvmName("putTrackIdToMetadataJson")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TrackIdToMetadataJsonProxy>
        .put(key: kotlin.String, value: kotlin.String) {
           _builder.putTrackIdToMetadataJson(key, value)
         }
      /**
       * `map<string, string> track_id_to_metadata_json = 2;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("setTrackIdToMetadataJson")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TrackIdToMetadataJsonProxy>
        .set(key: kotlin.String, value: kotlin.String) {
           put(key, value)
         }
      /**
       * `map<string, string> track_id_to_metadata_json = 2;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("removeTrackIdToMetadataJson")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TrackIdToMetadataJsonProxy>
        .remove(key: kotlin.String) {
           _builder.removeTrackIdToMetadataJson(key)
         }
      /**
       * `map<string, string> track_id_to_metadata_json = 2;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("putAllTrackIdToMetadataJson")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TrackIdToMetadataJsonProxy>
        .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
           _builder.putAllTrackIdToMetadataJson(map)
         }
      /**
       * `map<string, string> track_id_to_metadata_json = 2;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("clearTrackIdToMetadataJson")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TrackIdToMetadataJsonProxy>
        .clear() {
           _builder.clearTrackIdToMetadataJson()
         }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class TrackIdToBitratesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * Maps track_id to its bitrate. The track_id in the TrackBitrates message is ignored (we use the map key), so it can be ommited.
       * ```
       *
       * `map<string, .fishjam.media_events.peer.MediaEvent.TrackBitrates> track_id_to_bitrates = 3;`
       */
       public val trackIdToBitrates: com.google.protobuf.kotlin.DslMap<kotlin.String, fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates, TrackIdToBitratesProxy>
        @kotlin.jvm.JvmSynthetic
        @JvmName("getTrackIdToBitratesMap")
        get() = com.google.protobuf.kotlin.DslMap(
          _builder.getTrackIdToBitratesMap()
        )
      /**
       * ```
       * Maps track_id to its bitrate. The track_id in the TrackBitrates message is ignored (we use the map key), so it can be ommited.
       * ```
       *
       * `map<string, .fishjam.media_events.peer.MediaEvent.TrackBitrates> track_id_to_bitrates = 3;`
       */
      @JvmName("putTrackIdToBitrates")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates, TrackIdToBitratesProxy>
        .put(key: kotlin.String, value: fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates) {
           _builder.putTrackIdToBitrates(key, value)
         }
      /**
       * ```
       * Maps track_id to its bitrate. The track_id in the TrackBitrates message is ignored (we use the map key), so it can be ommited.
       * ```
       *
       * `map<string, .fishjam.media_events.peer.MediaEvent.TrackBitrates> track_id_to_bitrates = 3;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("setTrackIdToBitrates")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates, TrackIdToBitratesProxy>
        .set(key: kotlin.String, value: fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates) {
           put(key, value)
         }
      /**
       * ```
       * Maps track_id to its bitrate. The track_id in the TrackBitrates message is ignored (we use the map key), so it can be ommited.
       * ```
       *
       * `map<string, .fishjam.media_events.peer.MediaEvent.TrackBitrates> track_id_to_bitrates = 3;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("removeTrackIdToBitrates")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates, TrackIdToBitratesProxy>
        .remove(key: kotlin.String) {
           _builder.removeTrackIdToBitrates(key)
         }
      /**
       * ```
       * Maps track_id to its bitrate. The track_id in the TrackBitrates message is ignored (we use the map key), so it can be ommited.
       * ```
       *
       * `map<string, .fishjam.media_events.peer.MediaEvent.TrackBitrates> track_id_to_bitrates = 3;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("putAllTrackIdToBitrates")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates, TrackIdToBitratesProxy>
        .putAll(map: kotlin.collections.Map<kotlin.String, fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates>) {
           _builder.putAllTrackIdToBitrates(map)
         }
      /**
       * ```
       * Maps track_id to its bitrate. The track_id in the TrackBitrates message is ignored (we use the map key), so it can be ommited.
       * ```
       *
       * `map<string, .fishjam.media_events.peer.MediaEvent.TrackBitrates> track_id_to_bitrates = 3;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("clearTrackIdToBitrates")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates, TrackIdToBitratesProxy>
        .clear() {
           _builder.clearTrackIdToBitrates()
         }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class MidToTrackIdProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `map<string, string> mid_to_track_id = 4;`
       */
       public val midToTrackId: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MidToTrackIdProxy>
        @kotlin.jvm.JvmSynthetic
        @JvmName("getMidToTrackIdMap")
        get() = com.google.protobuf.kotlin.DslMap(
          _builder.getMidToTrackIdMap()
        )
      /**
       * `map<string, string> mid_to_track_id = 4;`
       */
      @JvmName("putMidToTrackId")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MidToTrackIdProxy>
        .put(key: kotlin.String, value: kotlin.String) {
           _builder.putMidToTrackId(key, value)
         }
      /**
       * `map<string, string> mid_to_track_id = 4;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("setMidToTrackId")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MidToTrackIdProxy>
        .set(key: kotlin.String, value: kotlin.String) {
           put(key, value)
         }
      /**
       * `map<string, string> mid_to_track_id = 4;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("removeMidToTrackId")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MidToTrackIdProxy>
        .remove(key: kotlin.String) {
           _builder.removeMidToTrackId(key)
         }
      /**
       * `map<string, string> mid_to_track_id = 4;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("putAllMidToTrackId")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MidToTrackIdProxy>
        .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
           _builder.putAllMidToTrackId(map)
         }
      /**
       * `map<string, string> mid_to_track_id = 4;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("clearMidToTrackId")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MidToTrackIdProxy>
        .clear() {
           _builder.clearMidToTrackId()
         }
    }
  }
  @kotlin.jvm.JvmName("-initializetrackBitrates")
  public inline fun trackBitrates(block: fishjam.media_events.peer.MediaEventKt.TrackBitratesKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates =
    fishjam.media_events.peer.MediaEventKt.TrackBitratesKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent when Peer wants to update its track's bitrate
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.TrackBitrates`
   */
  public object TrackBitratesKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates = _builder.build()

      /**
       * `string track_id = 1;`
       */
      public var trackId: kotlin.String
        @JvmName("getTrackId")
        get() = _builder.getTrackId()
        @JvmName("setTrackId")
        set(value) {
          _builder.setTrackId(value)
        }
      /**
       * `string track_id = 1;`
       */
      public fun clearTrackId() {
        _builder.clearTrackId()
      }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class VariantBitratesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * Bitrate of each variant. For non-simulcast tracks use VARIANT_UNSPECIFIED.
       * ```
       *
       * `repeated .fishjam.media_events.peer.MediaEvent.VariantBitrate variant_bitrates = 2;`
       */
       public val variantBitrates: com.google.protobuf.kotlin.DslList<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate, VariantBitratesProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.getVariantBitratesList()
        )
      /**
       * ```
       * Bitrate of each variant. For non-simulcast tracks use VARIANT_UNSPECIFIED.
       * ```
       *
       * `repeated .fishjam.media_events.peer.MediaEvent.VariantBitrate variant_bitrates = 2;`
       * @param value The variantBitrates to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addVariantBitrates")
      public fun com.google.protobuf.kotlin.DslList<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate, VariantBitratesProxy>.add(value: fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate) {
        _builder.addVariantBitrates(value)
      }
      /**
       * ```
       * Bitrate of each variant. For non-simulcast tracks use VARIANT_UNSPECIFIED.
       * ```
       *
       * `repeated .fishjam.media_events.peer.MediaEvent.VariantBitrate variant_bitrates = 2;`
       * @param value The variantBitrates to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignVariantBitrates")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate, VariantBitratesProxy>.plusAssign(value: fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate) {
        add(value)
      }
      /**
       * ```
       * Bitrate of each variant. For non-simulcast tracks use VARIANT_UNSPECIFIED.
       * ```
       *
       * `repeated .fishjam.media_events.peer.MediaEvent.VariantBitrate variant_bitrates = 2;`
       * @param values The variantBitrates to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllVariantBitrates")
      public fun com.google.protobuf.kotlin.DslList<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate, VariantBitratesProxy>.addAll(values: kotlin.collections.Iterable<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate>) {
        _builder.addAllVariantBitrates(values)
      }
      /**
       * ```
       * Bitrate of each variant. For non-simulcast tracks use VARIANT_UNSPECIFIED.
       * ```
       *
       * `repeated .fishjam.media_events.peer.MediaEvent.VariantBitrate variant_bitrates = 2;`
       * @param values The variantBitrates to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllVariantBitrates")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate, VariantBitratesProxy>.plusAssign(values: kotlin.collections.Iterable<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate>) {
        addAll(values)
      }
      /**
       * ```
       * Bitrate of each variant. For non-simulcast tracks use VARIANT_UNSPECIFIED.
       * ```
       *
       * `repeated .fishjam.media_events.peer.MediaEvent.VariantBitrate variant_bitrates = 2;`
       * @param index The index to set the value at.
       * @param value The variantBitrates to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setVariantBitrates")
      public operator fun com.google.protobuf.kotlin.DslList<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate, VariantBitratesProxy>.set(index: kotlin.Int, value: fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate) {
        _builder.setVariantBitrates(index, value)
      }
      /**
       * ```
       * Bitrate of each variant. For non-simulcast tracks use VARIANT_UNSPECIFIED.
       * ```
       *
       * `repeated .fishjam.media_events.peer.MediaEvent.VariantBitrate variant_bitrates = 2;`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearVariantBitrates")
      public fun com.google.protobuf.kotlin.DslList<fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate, VariantBitratesProxy>.clear() {
        _builder.clearVariantBitrates()
      }

    }
  }
  @kotlin.jvm.JvmName("-initializedisableTrackVariant")
  public inline fun disableTrackVariant(block: fishjam.media_events.peer.MediaEventKt.DisableTrackVariantKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant =
    fishjam.media_events.peer.MediaEventKt.DisableTrackVariantKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent when client disables one of the track variants
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.DisableTrackVariant`
   */
  public object DisableTrackVariantKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant = _builder.build()

      /**
       * `string track_id = 1;`
       */
      public var trackId: kotlin.String
        @JvmName("getTrackId")
        get() = _builder.getTrackId()
        @JvmName("setTrackId")
        set(value) {
          _builder.setTrackId(value)
        }
      /**
       * `string track_id = 1;`
       */
      public fun clearTrackId() {
        _builder.clearTrackId()
      }

      /**
       * `.fishjam.media_events.Variant variant = 2;`
       */
      public var variant: fishjam.media_events.Shared.Variant
        @JvmName("getVariant")
        get() = _builder.getVariant()
        @JvmName("setVariant")
        set(value) {
          _builder.setVariant(value)
        }
      public var variantValue: kotlin.Int
        @JvmName("getVariantValue")
        get() = _builder.getVariantValue()
        @JvmName("setVariantValue")
        set(value) {
          _builder.setVariantValue(value)
        }
      /**
       * `.fishjam.media_events.Variant variant = 2;`
       */
      public fun clearVariant() {
        _builder.clearVariant()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeenableTrackVariant")
  public inline fun enableTrackVariant(block: fishjam.media_events.peer.MediaEventKt.EnableTrackVariantKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant =
    fishjam.media_events.peer.MediaEventKt.EnableTrackVariantKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Sent when client enables one of the track variants
   * ```
   *
   * Protobuf type `fishjam.media_events.peer.MediaEvent.EnableTrackVariant`
   */
  public object EnableTrackVariantKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant = _builder.build()

      /**
       * `string track_id = 1;`
       */
      public var trackId: kotlin.String
        @JvmName("getTrackId")
        get() = _builder.getTrackId()
        @JvmName("setTrackId")
        set(value) {
          _builder.setTrackId(value)
        }
      /**
       * `string track_id = 1;`
       */
      public fun clearTrackId() {
        _builder.clearTrackId()
      }

      /**
       * `.fishjam.media_events.Variant variant = 2;`
       */
      public var variant: fishjam.media_events.Shared.Variant
        @JvmName("getVariant")
        get() = _builder.getVariant()
        @JvmName("setVariant")
        set(value) {
          _builder.setVariant(value)
        }
      public var variantValue: kotlin.Int
        @JvmName("getVariantValue")
        get() = _builder.getVariantValue()
        @JvmName("setVariantValue")
        set(value) {
          _builder.setVariantValue(value)
        }
      /**
       * `.fishjam.media_events.Variant variant = 2;`
       */
      public fun clearVariant() {
        _builder.clearVariant()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializesetTargetTrackVariant")
  public inline fun setTargetTrackVariant(block: fishjam.media_events.peer.MediaEventKt.SetTargetTrackVariantKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant =
    fishjam.media_events.peer.MediaEventKt.SetTargetTrackVariantKt.Dsl._create(fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `fishjam.media_events.peer.MediaEvent.SetTargetTrackVariant`
   */
  public object SetTargetTrackVariantKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant = _builder.build()

      /**
       * `string track_id = 1;`
       */
      public var trackId: kotlin.String
        @JvmName("getTrackId")
        get() = _builder.getTrackId()
        @JvmName("setTrackId")
        set(value) {
          _builder.setTrackId(value)
        }
      /**
       * `string track_id = 1;`
       */
      public fun clearTrackId() {
        _builder.clearTrackId()
      }

      /**
       * `.fishjam.media_events.Variant variant = 2;`
       */
      public var variant: fishjam.media_events.Shared.Variant
        @JvmName("getVariant")
        get() = _builder.getVariant()
        @JvmName("setVariant")
        set(value) {
          _builder.setVariant(value)
        }
      public var variantValue: kotlin.Int
        @JvmName("getVariantValue")
        get() = _builder.getVariantValue()
        @JvmName("setVariantValue")
        set(value) {
          _builder.setVariantValue(value)
        }
      /**
       * `.fishjam.media_events.Variant variant = 2;`
       */
      public fun clearVariant() {
        _builder.clearVariant()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.copy(block: `fishjam.media_events.peer`.MediaEventKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent =
  `fishjam.media_events.peer`.MediaEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate.copy(block: `fishjam.media_events.peer`.MediaEventKt.VariantBitrateKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.VariantBitrate =
  `fishjam.media_events.peer`.MediaEventKt.VariantBitrateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.Connect.copy(block: `fishjam.media_events.peer`.MediaEventKt.ConnectKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.Connect =
  `fishjam.media_events.peer`.MediaEventKt.ConnectKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.Disconnect.copy(block: `fishjam.media_events.peer`.MediaEventKt.DisconnectKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.Disconnect =
  `fishjam.media_events.peer`.MediaEventKt.DisconnectKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata.copy(block: `fishjam.media_events.peer`.MediaEventKt.UpdateEndpointMetadataKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata =
  `fishjam.media_events.peer`.MediaEventKt.UpdateEndpointMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata.copy(block: `fishjam.media_events.peer`.MediaEventKt.UpdateTrackMetadataKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata =
  `fishjam.media_events.peer`.MediaEventKt.UpdateTrackMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks.copy(block: `fishjam.media_events.peer`.MediaEventKt.RenegotiateTracksKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks =
  `fishjam.media_events.peer`.MediaEventKt.RenegotiateTracksKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.SdpOffer.copy(block: `fishjam.media_events.peer`.MediaEventKt.SdpOfferKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.SdpOffer =
  `fishjam.media_events.peer`.MediaEventKt.SdpOfferKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates.copy(block: `fishjam.media_events.peer`.MediaEventKt.TrackBitratesKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates =
  `fishjam.media_events.peer`.MediaEventKt.TrackBitratesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant.copy(block: `fishjam.media_events.peer`.MediaEventKt.DisableTrackVariantKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant =
  `fishjam.media_events.peer`.MediaEventKt.DisableTrackVariantKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant.copy(block: `fishjam.media_events.peer`.MediaEventKt.EnableTrackVariantKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant =
  `fishjam.media_events.peer`.MediaEventKt.EnableTrackVariantKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant.copy(block: `fishjam.media_events.peer`.MediaEventKt.SetTargetTrackVariantKt.Dsl.() -> kotlin.Unit): fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant =
  `fishjam.media_events.peer`.MediaEventKt.SetTargetTrackVariantKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.connectOrNull: fishjam.media_events.peer.Peer.MediaEvent.Connect?
  get() = if (hasConnect()) getConnect() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.disconnectOrNull: fishjam.media_events.peer.Peer.MediaEvent.Disconnect?
  get() = if (hasDisconnect()) getDisconnect() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.updateEndpointMetadataOrNull: fishjam.media_events.peer.Peer.MediaEvent.UpdateEndpointMetadata?
  get() = if (hasUpdateEndpointMetadata()) getUpdateEndpointMetadata() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.updateTrackMetadataOrNull: fishjam.media_events.peer.Peer.MediaEvent.UpdateTrackMetadata?
  get() = if (hasUpdateTrackMetadata()) getUpdateTrackMetadata() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.renegotiateTracksOrNull: fishjam.media_events.peer.Peer.MediaEvent.RenegotiateTracks?
  get() = if (hasRenegotiateTracks()) getRenegotiateTracks() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.candidateOrNull: fishjam.media_events.Shared.Candidate?
  get() = if (hasCandidate()) getCandidate() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.sdpOfferOrNull: fishjam.media_events.peer.Peer.MediaEvent.SdpOffer?
  get() = if (hasSdpOffer()) getSdpOffer() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.trackBitratesOrNull: fishjam.media_events.peer.Peer.MediaEvent.TrackBitrates?
  get() = if (hasTrackBitrates()) getTrackBitrates() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.enableTrackVariantOrNull: fishjam.media_events.peer.Peer.MediaEvent.EnableTrackVariant?
  get() = if (hasEnableTrackVariant()) getEnableTrackVariant() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.disableTrackVariantOrNull: fishjam.media_events.peer.Peer.MediaEvent.DisableTrackVariant?
  get() = if (hasDisableTrackVariant()) getDisableTrackVariant() else null

public val fishjam.media_events.peer.Peer.MediaEventOrBuilder.setTargetTrackVariantOrNull: fishjam.media_events.peer.Peer.MediaEvent.SetTargetTrackVariant?
  get() = if (hasSetTargetTrackVariant()) getSetTargetTrackVariant() else null

