
name: Android Build & lint
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: Download ktlint
        run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.1.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/

      - name: Run linter
        run: ktlint **/*.kt
        path: |
          /home/runner/work/react-native-client-sdk/packages/android-client

      - name: Build
        run: ./gradlew assembleRelease
        path: |
          /home/runner/work/react-native-client-sdk/packages/android-client

      - name: Test
        run: ./gradlew :FishjamClient:testDebugUnitTest
        path: |
          /home/runner/work/react-native-client-sdk/packages/android-client
