name: Android - Build & Lint

on:
  pull_request:
    paths:
      - packages/android-client/**

jobs:
  android_build_and_lint:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: Grant Execute Permissions
        run: chmod +x gradlew
        working-directory: ./packages/android-client

      - name: Build
        run: ./gradlew assembleRelease
        working-directory: ./packages/android-client

      - name: Test
        run: ./gradlew :FishjamClient:testDebugUnitTest
        working-directory: ./packages/android-client
