name: Android Deploy Docs
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: Build Docs
        run: ./gradlew dokkaHtml
        path: |
          /home/runner/work/react-native-client-sdk/packages/android-client

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: FishjamClient/build/dokka/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        path: |
          /home/runner/work/react-native-client-sdk/packages/android-client
