name: Lint & Types
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn
      - name: Install dependencies for example
        run: yarn
        working-directory: ./example
      - name: Install dependencies for example tests
        run: yarn
        working-directory: ./example/webdriverio-test
      - name: Check types
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Lint Example
        run: yarn lint
        working-directory: ./example
      - name: Build
        run: EXPO_NONINTERACTIVE=true yarn build
      - name: Build plugin
        run: EXPO_NONINTERACTIVE=true yarn build plugin
