# If for some reason release.yml fails for iOS or Android, but the spec is public, you can try to publish the React Native package manually.
name: Publish React Native Package
on:
  workflow_dispatch:

jobs:
  publish-react-native-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish React Native Client
        uses: ./.github/actions/publish-react-native-client
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
