name: React Native - Unit tests
on:
  pull_request:
jobs:
  rn-client-unit-tests:
    runs-on: [self-hosted, macOS]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: Use corepack
        run: corepack enable
      - name: Install node dependencies
        run: yarn
      - name: Run unit tests for the library
        run: yarn test -- src/__tests__/*.test.tsx
        working-directory: ./packages/react-native-client
