name: Release mobile packages

on:
  push:
    branches:
      - main
    tags:
      -  '*'

jobs:
  release-mobile-packages:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push FishjamClient.podspec




